steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--build-arg=NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}"
      - "--build-arg=SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY}"
      - "-t"
      - "${_IMAGE}"
      - "."
images:
  - "${_IMAGE}"
timeout: 2400s
options:
  machineType: E2_HIGHCPU_8
