import type { KnowledgeEntrySeed } from "./types";

/**
 * Curated, approved Novalyte AI business knowledge for the live call copilot.
 * Sourced from: discovery doc, public site FAQs, call-scripts, calls.tsx playbook.
 * Do NOT auto-ingest unreviewed files — update here or via admin UI after approval.
 */
export const APPROVED_KNOWLEDGE_SEED: KnowledgeEntrySeed[] = [
  {
    id: "company-identity-001",
    category: "company_identity",
    title: "What is Novalyte AI",
    content:
      "Novalyte AI is a healthcare technology facilitator — not a medical provider, clinic, pharmacy, or diagnostic service. We connect patient demand, verified men's health clinics, workforce, and operational services through one ecosystem. We do not diagnose, prescribe, or provide medical advice. Licensed clinics remain responsible for all medical decisions and compliance.",
    tags: ["novalyte", "identity", "positioning"],
    keywords: ["novalyte ai", "what is novalyte", "who are you", "what do you do", "company"],
    callStages: ["opening", "purpose"],
    sourceFile: "z.ai-novalyte-new-homepage/README.md",
    sourceSection: "Legal positioning",
    externalApproved: true,
    confidence: 0.98,
  },
  {
    id: "directory-pricing-001",
    category: "clinic_directory",
    title: "Free directory listing",
    content:
      "The basic verified clinic directory listing is free. There is no charge to apply, verify public clinic details, or publish an approved profile. Optional paid services — such as performance-based patient acquisition, advertising, workforce, or marketplace — are separate and only discussed if the clinic asks or after permission for the free listing is handled.",
    tags: ["directory", "free", "pricing", "permission"],
    keywords: ["free", "fee", "fees", "cost", "charge", "listing free", "catch", "pay"],
    callStages: ["purpose", "permission"],
    sourceFile: "z.ai-novalyte-new-homepage/src/lib/clinic-faqs.ts",
    sourceSection: "Is the clinic directory listing free?",
    externalApproved: true,
    confidence: 0.99,
  },
  {
    id: "directory-what-001",
    category: "clinic_directory",
    title: "What the directory is",
    content:
      "The Novalyte AI Verified Clinic Directory helps men searching for TRT, hormone optimization, and related men's health care find appropriate local providers. Listings show public clinic information patients need: services, locations, providers, hours, booking method, and verification status. A clinic is listed only after explicit permission and review — never automatically.",
    tags: ["directory", "patients", "verification"],
    keywords: ["directory", "listing", "profile", "patients find", "men's health", "trt"],
    callStages: ["purpose", "permission", "verification"],
    sourceFile: "docs/NOVALYTE_UNIFIED_COMMAND_CENTER_DISCOVERY.md",
    sourceSection: "Publication boundary",
    externalApproved: true,
    confidence: 0.95,
  },
  {
    id: "outreach-purpose-001",
    category: "clinic_outreach",
    title: "Why we call clinics (first call objective)",
    content:
      "The first outreach call is primarily to: (1) reach the right person, (2) briefly explain Novalyte AI, (3) ask permission to include the clinic in our free verified directory, (4) verify basic public information, (5) confirm preferred booking method, (6) identify the listing contact, and (7) agree on a follow-up step. This is not an aggressive sale of expensive services on the first call.",
    tags: ["outreach", "first call", "objective"],
    keywords: ["why calling", "why are you calling", "reason for call", "what do you want", "purpose"],
    callStages: ["opening", "purpose", "permission"],
    sourceFile: "docs/NOVALYTE_UNIFIED_COMMAND_CENTER_DISCOVERY.md",
    sourceSection: "Prospect workflow",
    externalApproved: true,
    confidence: 0.97,
  },
  {
    id: "outreach-not-sales-001",
    category: "objection_handling",
    title: "Is this a sales call",
    content:
      "If asked whether this is a sales call: clarify that today's call is about a free, permission-based directory verification — not a paid contract. Novalyte AI may offer optional patient-acquisition services later, but only if the clinic is interested. The immediate ask is permission to list verified public clinic details so patients can find them.",
    tags: ["objection", "sales", "marketing"],
    keywords: ["sales call", "selling", "marketing", "did not request", "spam", "solicitation"],
    callStages: ["purpose", "permission"],
    sourceFile: "src/components/admin/views/calls.tsx",
    sourceSection: "OBJECTION_LIBRARY / field guide",
    externalApproved: true,
    confidence: 0.96,
  },
  {
    id: "patient-acquisition-001",
    category: "patient_acquisition",
    title: "How patient acquisition works (approved claims)",
    content:
      "Novalyte AI can help clinics improve visibility and route high-intent men's health inquiries through educational content, assessments, and structured intake. Availability varies by market. We do NOT guarantee a specific number of patients, bookings, revenue, or clinical outcomes. Any optional paid acquisition is performance-oriented and discussed separately from the free directory listing.",
    tags: ["patients", "acquisition", "leads"],
    keywords: ["bring patients", "patient leads", "how do you get patients", "patient acquisition", "referrals"],
    callStages: ["purpose", "qualification"],
    sourceFile: "z.ai-novalyte-new-homepage/src/lib/clinic-faqs.ts",
    sourceSection: "How can Novalyte help clinics attract qualified patients?",
    externalApproved: true,
    confidence: 0.94,
  },
  {
    id: "compliance-no-guarantee-001",
    category: "compliance",
    title: "Prohibited guarantees",
    content:
      "Never guarantee patient volume, revenue, conversion rates, traffic statistics, or clinical outcomes unless verified data is on record. Never claim a clinic has officially partnered with Novalyte AI unless documented. Never claim HIPAA compliance certifications or access to patient medical records that Novalyte AI does not have.",
    tags: ["compliance", "guarantees", "prohibited"],
    keywords: ["guarantee", "guaranteed", "promise", "how many patients", "roi", "results"],
    callStages: ["purpose", "qualification", "closing"],
    sourceFile: "z.ai-novalyte-new-homepage/src/lib/clinic-faqs.ts",
    sourceSection: "Does Novalyte guarantee leads, revenue, or clinical outcomes?",
    externalApproved: true,
    confidence: 0.99,
  },
  {
    id: "compliance-hipaa-001",
    category: "compliance",
    title: "HIPAA and patient data",
    content:
      "For directory verification we only need public clinic information and permission to publish it. Novalyte AI does not need access to patient medical records for a free listing. For sensitive compliance questions (HIPAA, legal, security certifications), do not improvise — offer to confirm in writing and follow up by email with approved materials.",
    tags: ["compliance", "hipaa", "privacy", "data"],
    keywords: ["hipaa", "patient records", "patient information", "medical records", "privacy", "data"],
    callStages: ["verification", "follow_up"],
    sourceFile: "z.ai-novalyte-new-homepage/README.md",
    sourceSection: "Trust, Privacy & Compliance",
    externalApproved: true,
    confidence: 0.92,
  },
  {
    id: "qualification-first-call-001",
    category: "qualification",
    title: "Information to collect on first call",
    content:
      "Priority on the first call: permission to list, listing contact name and role, public clinic name and phone, address, core services (TRT, GLP-1, telehealth, etc.), booking URL or phone booking method, accepting-new-patients status, and best email for verification follow-up. Provider credentials and photos can be collected later via intake form.",
    tags: ["qualification", "checklist", "verification"],
    keywords: ["what do you need", "information", "verify", "confirm", "details", "checklist"],
    callStages: ["verification", "qualification"],
    sourceFile: "src/components/admin/views/call-scripts.tsx",
    sourceSection: "Permission-to-List — collect info",
    externalApproved: true,
    confidence: 0.95,
  },
  {
    id: "objection-email-001",
    category: "objection_handling",
    title: "Send me an email",
    content:
      "Absolutely — before sending, confirm the best email and the name of the person who manages the clinic listing. Offer a one-page directory overview and verification next steps. Ask whether a brief follow-up call after they review would be helpful.",
    tags: ["objection", "email", "follow-up"],
    keywords: ["email", "send me", "send info", "mail", "write to us"],
    callStages: ["follow_up", "closing"],
    sourceFile: "src/components/admin/views/calls.tsx",
    sourceSection: "OBJECTION_LIBRARY",
    externalApproved: true,
    confidence: 0.96,
  },
  {
    id: "objection-busy-001",
    category: "objection_handling",
    title: "Bad time / call back",
    content:
      "Acknowledge they're busy. Offer a two-minute verification call at a better time, or offer to send a short email summary. Ask for the best day, time, and contact for the listing decision-maker.",
    tags: ["objection", "busy", "callback"],
    keywords: ["busy", "bad time", "call back", "later", "not a good time"],
    callStages: ["opening", "follow_up"],
    sourceFile: "src/components/admin/views/calls.tsx",
    sourceSection: "Field guide",
    externalApproved: true,
    confidence: 0.95,
  },
  {
    id: "objection-enough-patients-001",
    category: "objection_handling",
    title: "We already have enough patients",
    content:
      "Acknowledge that's a good problem to have. Explain the free directory still helps the right patients find them when capacity opens, and there is no cost or obligation. The immediate ask remains permission to publish verified public details — they can decline optional paid services entirely.",
    tags: ["objection", "capacity", "full"],
    keywords: ["enough patients", "full", "booked", "no room", "not taking patients"],
    callStages: ["permission", "objections"],
    sourceFile: "src/components/admin/views/calls.tsx",
    sourceSection: "Field guide",
    externalApproved: true,
    confidence: 0.93,
  },
  {
    id: "objection-not-interested-001",
    category: "objection_handling",
    title: "Not interested",
    content:
      "Respect the decision. Clarify there is no cost for the directory listing and no obligation. Ask if they'd prefer no further calls, or if they'd like a one-page email to review later. End politely if they decline.",
    tags: ["objection", "decline"],
    keywords: ["not interested", "no thanks", "don't call", "remove us"],
    callStages: ["closing"],
    sourceFile: "src/components/admin/views/calls.tsx",
    sourceSection: "Field guide",
    externalApproved: true,
    confidence: 0.94,
  },
  {
    id: "objection-owner-unavailable-001",
    category: "objection_handling",
    title: "Owner or manager not available",
    content:
      "Thank the front desk. Ask who manages the clinic's public listing or marketing decisions, the best time to reach them, and whether you may send a brief verification email. Do not push past a gatekeeper who cannot grant permission.",
    tags: ["objection", "gatekeeper", "owner"],
    keywords: ["owner", "manager", "doctor", "decision maker", "not here", "unavailable"],
    callStages: ["opening", "permission"],
    sourceFile: "src/components/admin/views/calls.tsx",
    sourceSection: "Field guide",
    externalApproved: true,
    confidence: 0.95,
  },
  {
    id: "directory-review-remove-001",
    category: "clinic_directory",
    title: "Review before publish and removal",
    content:
      "Clinics may review listing details before publication when requested. Listings are permission-based — a clinic can ask to update or remove their profile. Novalyte AI publishes only after explicit permission and internal verification review.",
    tags: ["directory", "review", "remove", "approve"],
    keywords: ["review first", "approve listing", "remove listing", "take down", "update listing"],
    callStages: ["permission", "verification", "closing"],
    sourceFile: "docs/NOVALYTE_UNIFIED_COMMAND_CENTER_DISCOVERY.md",
    sourceSection: "Publication workflow",
    externalApproved: true,
    confidence: 0.94,
  },
  {
    id: "services-optional-paid-001",
    category: "clinic_services",
    title: "Optional paid services (separate from free listing)",
    content:
      "Available now as optional, separate offerings: performance-based patient acquisition campaigns, advertising support, workforce hub, and marketplace services — each with its own terms and fees. In development / roadmap items must not be presented as live products. The free directory listing does not require purchasing any paid service.",
    tags: ["services", "paid", "roadmap"],
    keywords: ["advertising", "paid leads", "performance", "agency", "marketplace", "workforce"],
    callStages: ["purpose", "qualification"],
    sourceFile: "z.ai-novalyte-new-homepage/src/lib/clinic-faqs.ts",
    sourceSection: "Optional services",
    externalApproved: true,
    confidence: 0.93,
  },
  {
    id: "permission-granted-001",
    category: "qualification",
    title: "Clinic grants permission to list",
    content:
      "When permission is granted: thank them, confirm the public phone, address, core services, booking method, accepting-new-patients status, and best email for the verification link. Summarize what will appear publicly and explain the review step before publication.",
    tags: ["permission", "closing", "verification"],
    keywords: ["yes list", "permission", "go ahead", "you can list", "sounds good"],
    callStages: ["permission", "verification", "closing"],
    sourceFile: "src/components/admin/views/call-scripts.tsx",
    sourceSection: "Permission-to-List — If yes",
    externalApproved: true,
    confidence: 0.96,
  },
  {
    id: "low-confidence-fallback-001",
    category: "compliance",
    title: "Safe fallback when unsure",
    content:
      "If you are not certain of the accurate answer, say: 'I want to make sure I give you the correct information — let me confirm that and follow up with you by email.' Never invent statistics, partnerships, compliance certifications, or product capabilities.",
    tags: ["fallback", "escalation"],
    keywords: ["unsure", "unknown", "legal", "contract", "certified"],
    callStages: ["follow_up", "closing"],
    sourceFile: "internal/copilot-guardrails",
    sourceSection: "Hallucination protection",
    externalApproved: true,
    confidence: 0.99,
  },
];
