import type { DemandCampaignOpportunity } from "@/lib/demand/opportunities";

const now = "2026-07-23T18:00:00.000Z";

/** Seed opportunities for admin DI → Campaign Studio workflow (mock until live SEO feed). */
export const mockCampaignOpportunities: DemandCampaignOpportunity[] = [
  {
    id: "opp-phoenix-trt-cost",
    query: "how much does TRT cost in Phoenix",
    keywordCluster: "trt-cost-phoenix",
    treatmentSlug: "trt",
    city: "Phoenix",
    state: "Arizona",
    stateAbbreviation: "AZ",
    searchVolume: 720,
    cpc: 18.4,
    competition: 0.62,
    trendDirection: "rising",
    searchIntent: "cost",
    risingLocation: true,
    suggestedCampaignSlug: "phoenix-trt-july",
    suggestedPath: "/ads/trt/phoenix-az",
    suggestedHeroHeading: "Explore Testosterone Care Options in Phoenix",
    suggestedEyebrow: "Phoenix, Arizona · Testosterone Care",
    suggestedShortAnswerQuestions: [
      "How much does TRT cost in Phoenix?",
      "Does insurance cover TRT in Arizona?",
      "Is TRT telehealth available in Arizona?",
    ],
    suggestedAssessmentSlug: "testosterone-replacement-therapy",
    suggestedDirectoryFilters: { view: "directory", q: "testosterone", state: "AZ", city: "Phoenix" },
    contentStatus: "approved",
    complianceStatus: "cleared",
    publicationStatus: "ready_to_publish",
    lastReviewed: "2026-07-23",
    notes: "Sample opportunity aligned to live ads lander.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "opp-dallas-trt",
    query: "TRT clinics in Dallas",
    keywordCluster: "trt-clinics-dallas",
    treatmentSlug: "trt",
    city: "Dallas",
    state: "Texas",
    stateAbbreviation: "TX",
    searchVolume: 880,
    cpc: 16.1,
    competition: 0.55,
    trendDirection: "rising",
    searchIntent: "provider-search",
    risingLocation: true,
    suggestedPath: "/ads/trt/dallas-tx",
    suggestedHeroHeading: "Explore Testosterone Care Options in Dallas",
    suggestedAssessmentSlug: "testosterone-replacement-therapy",
    suggestedDirectoryFilters: { view: "directory", q: "testosterone", state: "TX", city: "Dallas" },
    contentStatus: "in_review",
    complianceStatus: "unchecked",
    publicationStatus: "not_ready",
    lastReviewed: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "opp-palo-alto-sexual-health",
    query: "sexual health clinic Palo Alto",
    keywordCluster: "sexual-health-palo-alto",
    treatmentSlug: "sexual-health",
    city: "Palo Alto",
    state: "California",
    stateAbbreviation: "CA",
    searchVolume: 390,
    cpc: 22.0,
    competition: 0.48,
    trendDirection: "stable",
    searchIntent: "provider-search",
    suggestedPath: "/ads/sexual-health/palo-alto-ca",
    suggestedHeroHeading: "Explore Sexual Health Care Options in Palo Alto",
    suggestedAssessmentSlug: "erectile-dysfunction",
    contentStatus: "drafted",
    complianceStatus: "unchecked",
    publicationStatus: "not_ready",
    lastReviewed: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "opp-beverly-hills-longevity",
    query: "longevity clinic Beverly Hills",
    keywordCluster: "longevity-beverly-hills",
    treatmentSlug: "longevity",
    city: "Beverly Hills",
    state: "California",
    stateAbbreviation: "CA",
    searchVolume: 510,
    cpc: 28.5,
    competition: 0.71,
    trendDirection: "rising",
    searchIntent: "provider-search",
    risingLocation: true,
    suggestedPath: "/ads/longevity/beverly-hills-ca",
    suggestedHeroHeading: "Explore Longevity Options in Beverly Hills",
    suggestedAssessmentSlug: "longevity-medicine",
    contentStatus: "detected",
    complianceStatus: "unchecked",
    publicationStatus: "not_ready",
    lastReviewed: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "opp-miami-hair",
    query: "hair restoration Miami",
    keywordCluster: "hair-miami",
    treatmentSlug: "hair-restoration",
    city: "Miami",
    state: "Florida",
    stateAbbreviation: "FL",
    searchVolume: 640,
    cpc: 14.2,
    competition: 0.58,
    trendDirection: "stable",
    searchIntent: "provider-search",
    suggestedPath: "/ads/hair-restoration/miami-fl",
    suggestedAssessmentSlug: "hair-restoration",
    contentStatus: "detected",
    complianceStatus: "flagged",
    publicationStatus: "not_ready",
    notes: "Needs compliance review before drafting hero claims.",
    lastReviewed: null,
    createdAt: now,
    updatedAt: now,
  },
];
