import type { ClinicIntelligenceProfile, ClinicIntelligenceSource } from "./types";

function asArray<T = string>(val: unknown): T[] {
  if (Array.isArray(val)) return val as T[];
  return [];
}

export function mapDbProfile(row: any, sources: any[] = []): ClinicIntelligenceProfile {
  return {
    id: row.id,
    clinicId: row.clinic_id,
    researchStatus: row.research_status,
    fitStatus: row.fit_status,
    fitScore: row.fit_score,
    priority: row.priority,
    shortSummary: row.short_summary,
    detailedSummary: row.detailed_summary,
    primaryCategory: row.primary_category,
    secondaryCategories: asArray(row.secondary_categories),
    services: asArray(row.services),
    audience: asArray(row.audience),
    careDelivery: asArray(row.care_delivery),
    address: row.address,
    city: row.city,
    state: row.state,
    postalCode: row.postal_code,
    county: row.county,
    serviceArea: asArray(row.service_area),
    websiteUrl: row.website_url,
    bookingUrl: row.booking_url,
    contactUrl: row.contact_url,
    phoneNumbers: asArray(row.phone_numbers),
    emailAddresses: asArray(row.email_addresses),
    providers: asArray(row.providers),
    leadership: asArray(row.leadership),
    likelyDecisionMakers: asArray(row.likely_decision_makers),
    differentiators: asArray(row.differentiators),
    notableFacts: asArray(row.notable_facts),
    accreditations: asArray(row.accreditations),
    yearsInBusiness: row.years_in_business,
    novalyteFitReason: row.novalyte_fit_reason,
    recommendedDirectoryCategories: asArray(row.recommended_directory_categories),
    relevantCampaigns: asArray(row.relevant_campaigns),
    conversationFocus: row.conversation_focus,
    personalizedOpening: row.personalized_opening,
    relevanceStatement: row.relevance_statement,
    verificationQuestions: asArray(row.verification_questions),
    objectionPreparation: asArray(row.objection_preparation),
    recommendedOutcome: row.recommended_outcome,
    recommendedNextAction: row.recommended_next_action,
    talkTrack: row.talk_track && typeof row.talk_track === "object" ? row.talk_track : {},
    missingInformation: asArray(row.missing_information),
    warnings: asArray(row.warnings),
    researchCompleteness: Number(row.research_completeness ?? 0),
    researchConfidence: row.research_confidence != null ? Number(row.research_confidence) : null,
    lastResearchedAt: row.last_researched_at,
    lastVerifiedAt: row.last_verified_at,
    lockedFields: asArray(row.locked_fields),
    generatedBy: row.generated_by,
    reviewedBy: row.reviewed_by,
    reviewedAt: row.reviewed_at,
    lastError: row.last_error,
    sources: sources.map(
      (s): ClinicIntelligenceSource => ({
        id: s.id,
        sourceUrl: s.source_url,
        pageTitle: s.page_title,
        sourceType: s.source_type,
        retrievedAt: s.retrieved_at,
        excerpt: s.excerpt,
        confidence: s.confidence,
        isOfficial: Boolean(s.is_official),
        humanReviewed: Boolean(s.human_reviewed),
      }),
    ),
  };
}
