-- Clinic intelligence profiles for founder-led pre-call briefing
-- Applied remotely; kept in-repo for reproducibility.

create table if not exists clinic_intelligence_profiles (
  id text primary key default gen_random_uuid()::text,
  clinic_id text not null unique references prospect_clinics(id) on delete cascade,
  research_status text not null default 'not_started'
    check (research_status in ('not_started','queued','researching','needs_review','verified','failed','stale')),
  fit_status text not null default 'research_required'
    check (fit_status in ('strong_fit','possible_fit','research_required','not_relevant','duplicate','invalid')),
  fit_score integer,
  priority text not null default 'medium'
    check (priority in ('high','medium','low','exclude')),
  short_summary text,
  detailed_summary text,
  primary_category text,
  secondary_categories jsonb not null default '[]'::jsonb,
  services jsonb not null default '[]'::jsonb,
  audience jsonb not null default '[]'::jsonb,
  care_delivery jsonb not null default '[]'::jsonb,
  address text,
  city text,
  state text,
  postal_code text,
  county text,
  service_area jsonb not null default '[]'::jsonb,
  website_url text,
  booking_url text,
  contact_url text,
  phone_numbers jsonb not null default '[]'::jsonb,
  email_addresses jsonb not null default '[]'::jsonb,
  providers jsonb not null default '[]'::jsonb,
  leadership jsonb not null default '[]'::jsonb,
  likely_decision_makers jsonb not null default '[]'::jsonb,
  differentiators jsonb not null default '[]'::jsonb,
  notable_facts jsonb not null default '[]'::jsonb,
  accreditations jsonb not null default '[]'::jsonb,
  years_in_business text,
  novalyte_fit_reason text,
  recommended_directory_categories jsonb not null default '[]'::jsonb,
  relevant_campaigns jsonb not null default '[]'::jsonb,
  conversation_focus text,
  personalized_opening text,
  relevance_statement text,
  verification_questions jsonb not null default '[]'::jsonb,
  objection_preparation jsonb not null default '[]'::jsonb,
  recommended_outcome text,
  recommended_next_action text,
  talk_track jsonb not null default '{}'::jsonb,
  missing_information jsonb not null default '[]'::jsonb,
  warnings jsonb not null default '[]'::jsonb,
  research_completeness integer not null default 0,
  research_confidence numeric,
  last_researched_at timestamptz,
  last_verified_at timestamptz,
  next_review_at timestamptz,
  field_provenance jsonb not null default '{}'::jsonb,
  locked_fields jsonb not null default '[]'::jsonb,
  generated_by text,
  reviewed_by text,
  reviewed_at timestamptz,
  raw_scrape_excerpt text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists clinic_intelligence_sources (
  id text primary key default gen_random_uuid()::text,
  profile_id text not null references clinic_intelligence_profiles(id) on delete cascade,
  clinic_id text not null references prospect_clinics(id) on delete cascade,
  source_url text not null,
  page_title text,
  source_type text not null default 'clinic_website',
  retrieved_at timestamptz not null default now(),
  excerpt text,
  confidence text not null default 'medium',
  is_official boolean not null default true,
  human_reviewed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists clinic_research_jobs (
  id text primary key default gen_random_uuid()::text,
  market_sprint_id text references market_sprints(id) on delete set null,
  status text not null default 'queued',
  total integer not null default 0,
  completed integer not null default 0,
  succeeded integer not null default 0,
  failed integer not null default 0,
  clinic_ids jsonb not null default '[]'::jsonb,
  errors jsonb not null default '[]'::jsonb,
  created_by text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
